# Generated by Django 4.0.4 on 2022-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
